database:
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  port: 5432
  host: 127.0.0.1
application:
  port: 8000
  hmac_secret: "Some-really-long-and-super-secret-string"
email_client: 
  authorization_token: "my-secret-token"
  timeout_millis: 10000
