application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
  hmac_secret: "Some-really-long-and-super-secret-string"
database:
  require_ssl: false
email_client:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
