application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
database:
  require_ssl: false
email_client:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
oidc: 
  client_id: "some_client_id"
  client_secret: "very_secret12345"
  issuer_url: "https://accounts.google.com"
  redirect_uri: "http://localhost/login/callback"
  timeout_millis: 10000
